// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Restify.Core.Infrastructure.Persistence;

#nullable disable

namespace Restify.Core.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    [Migration("20260115143252_AddGeneralTablesAndValues")]
    partial class AddGeneralTablesAndValues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("core")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Restify.Core.Domain.Entities.GeneralTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicationCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ExtraConfig")
                        .HasColumnType("jsonb");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("GeneralTables", "core");
                });

            modelBuilder.Entity("Restify.Core.Domain.Entities.GeneralValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BackgroundColor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ExtraConfig")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("GeneralTableId")
                        .HasColumnType("uuid");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("NumericValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Reference1")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Reference2")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Reference3")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Reference4")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Reference5")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TextColor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GeneralTableId");

                    b.HasIndex("TenantId", "GeneralTableId", "Code")
                        .IsUnique();

                    b.ToTable("GeneralValues", "core");
                });

            modelBuilder.Entity("Restify.Core.Domain.Entities.GridColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Alignment")
                        .HasColumnType("integer");

                    b.Property<string>("CellTemplate")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("ColumnType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CssClass")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DisplayFormat")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EditorTemplate")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("EditorType")
                        .HasColumnType("integer");

                    b.Property<string>("EnabledCondition")
                        .HasColumnType("jsonb");

                    b.Property<string>("ExtraConfig")
                        .HasColumnType("jsonb");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("FormColumnSpan")
                        .HasColumnType("integer");

                    b.Property<string>("FormGroup")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FormLabel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("FormOrder")
                        .HasColumnType("integer");

                    b.Property<string>("FrozenPosition")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("GridConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<int>("GridOrder")
                        .HasColumnType("integer");

                    b.Property<string>("HeaderText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("HeaderTooltip")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("HelpText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsExportable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFilterable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFrozen")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInlineEditable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimaryKey")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSearchable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSortable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVisibleInCreate")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVisibleInEdit")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVisibleInGrid")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVisibleInView")
                        .HasColumnType("boolean");

                    b.Property<string>("MaxWidth")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MinWidth")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Placeholder")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Prefix")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SelectOptions")
                        .HasColumnType("jsonb");

                    b.Property<string>("Suffix")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("VisibilityCondition")
                        .HasColumnType("jsonb");

                    b.Property<string>("Width")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("GridConfigurationId", "GridOrder");

                    b.ToTable("GridColumns", "core");
                });

            modelBuilder.Entity("Restify.Core.Domain.Entities.GridColumnLookup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalDisplayFields")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("AllowAdd")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowClear")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowSearch")
                        .HasColumnType("boolean");

                    b.Property<string>("ApiEndpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("CacheDuration")
                        .HasColumnType("integer");

                    b.Property<bool>("ClearOnParentChange")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DisplayField")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("name");

                    b.Property<string>("DisplayFormat")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("GridColumnId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCached")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDependentLookup")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxItems")
                        .HasColumnType("integer");

                    b.Property<int>("MinSearchLength")
                        .HasColumnType("integer");

                    b.Property<string>("OrderBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ParentField")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ParentFilterField")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("PreloadData")
                        .HasColumnType("boolean");

                    b.Property<string>("SearchField")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StaticFilter")
                        .HasColumnType("jsonb");

                    b.Property<string>("TargetEntity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("ValueField")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("id");

                    b.HasKey("Id");

                    b.HasIndex("GridColumnId")
                        .IsUnique();

                    b.ToTable("GridColumnLookups", "core");
                });

            modelBuilder.Entity("Restify.Core.Domain.Entities.GridColumnValidation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ClientOnly")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("GridColumnId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<bool>("ServerOnly")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<int>("ValidationType")
                        .HasColumnType("integer");

                    b.Property<string>("ValidationValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ValidationValue2")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("GridColumnId", "Order");

                    b.ToTable("GridColumnValidations", "core");
                });

            modelBuilder.Entity("Restify.Core.Domain.Entities.GridConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowAdvancedFilter")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowColumnReorder")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowColumnResize")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowColumnToggle")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowCreate")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowDelete")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowEdit")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowExport")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowImport")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowInlineEdit")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowMultiSelect")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowSearch")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowView")
                        .HasColumnType("boolean");

                    b.Property<string>("ApiEndpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("DefaultPageSize")
                        .HasColumnType("integer");

                    b.Property<string>("DefaultSortColumn")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("DefaultSortDescending")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DisplayNamePlural")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ExportFormats")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ExtraConfig")
                        .HasColumnType("jsonb");

                    b.Property<string>("FormMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("modal");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MenuOrder")
                        .HasColumnType("integer");

                    b.Property<string>("MenuPath")
                        .HasColumnType("text");

                    b.Property<string>("PageSizeOptions")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RequiredPermission")
                        .HasColumnType("text");

                    b.Property<string>("RowActionsPosition")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("end");

                    b.Property<bool>("ShowRowActions")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "EntityName")
                        .IsUnique();

                    b.ToTable("GridConfigurations", "core");
                });

            modelBuilder.Entity("Restify.Core.Domain.Entities.GeneralTable", b =>
                {
                    b.HasOne("Restify.Core.Domain.Entities.GeneralTable", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Restify.Core.Domain.Entities.GeneralValue", b =>
                {
                    b.HasOne("Restify.Core.Domain.Entities.GeneralTable", "GeneralTable")
                        .WithMany("Values")
                        .HasForeignKey("GeneralTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneralTable");
                });

            modelBuilder.Entity("Restify.Core.Domain.Entities.GridColumn", b =>
                {
                    b.HasOne("Restify.Core.Domain.Entities.GridConfiguration", "GridConfiguration")
                        .WithMany("Columns")
                        .HasForeignKey("GridConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GridConfiguration");
                });

            modelBuilder.Entity("Restify.Core.Domain.Entities.GridColumnLookup", b =>
                {
                    b.HasOne("Restify.Core.Domain.Entities.GridColumn", "GridColumn")
                        .WithOne("Lookup")
                        .HasForeignKey("Restify.Core.Domain.Entities.GridColumnLookup", "GridColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GridColumn");
                });

            modelBuilder.Entity("Restify.Core.Domain.Entities.GridColumnValidation", b =>
                {
                    b.HasOne("Restify.Core.Domain.Entities.GridColumn", "GridColumn")
                        .WithMany("Validations")
                        .HasForeignKey("GridColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GridColumn");
                });

            modelBuilder.Entity("Restify.Core.Domain.Entities.GeneralTable", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("Restify.Core.Domain.Entities.GridColumn", b =>
                {
                    b.Navigation("Lookup");

                    b.Navigation("Validations");
                });

            modelBuilder.Entity("Restify.Core.Domain.Entities.GridConfiguration", b =>
                {
                    b.Navigation("Columns");
                });
#pragma warning restore 612, 618
        }
    }
}
